// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBt8yrFXcLxe4ptg-oOOMKXW5q0CfHuuyI',
    appId: '1:913204060083:web:defd6ecedda7a93a2475c6',
    messagingSenderId: '913204060083',
    projectId: 'ecommerce-adc94',
    authDomain: 'ecommerce-adc94.firebaseapp.com',
    storageBucket: 'ecommerce-adc94.appspot.com',
    measurementId: 'G-Y9DBX0H8HL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_R2yiHDqQxyB6EBJ3gY6EkTdGQ91e2Nc',
    appId: '1:913204060083:android:a3d4846ce75c04902475c6',
    messagingSenderId: '913204060083',
    projectId: 'ecommerce-adc94',
    storageBucket: 'ecommerce-adc94.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJWXOdK7Ashwo5--ds4aZqdqvRyZ_C5Eg',
    appId: '1:913204060083:ios:92bd51d6798e38092475c6',
    messagingSenderId: '913204060083',
    projectId: 'ecommerce-adc94',
    storageBucket: 'ecommerce-adc94.appspot.com',
    iosBundleId: 'com.example.untitled1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJWXOdK7Ashwo5--ds4aZqdqvRyZ_C5Eg',
    appId: '1:913204060083:ios:92bd51d6798e38092475c6',
    messagingSenderId: '913204060083',
    projectId: 'ecommerce-adc94',
    storageBucket: 'ecommerce-adc94.appspot.com',
    iosBundleId: 'com.example.untitled1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBt8yrFXcLxe4ptg-oOOMKXW5q0CfHuuyI',
    appId: '1:913204060083:web:6f1e9550066e3fee2475c6',
    messagingSenderId: '913204060083',
    projectId: 'ecommerce-adc94',
    authDomain: 'ecommerce-adc94.firebaseapp.com',
    storageBucket: 'ecommerce-adc94.appspot.com',
    measurementId: 'G-F8YEEKW99X',
  );
}
